name: Build and deploy JAR app to Render - back-ame-en-harmonie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set env variables for tests
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "CLIENT_URL=${{ vars.CLIENT_URL }}" >> $GITHUB_ENV
          echo "URI_MONGO=${{ secrets.URI_MONGO }}" >> $GITHUB_ENV
          echo "DB_MONGO=test" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install -DskipTests=false -Dmaven.test.failure.ignore=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app
      - name: Trigger Render deployment
        run: |
         curl -X POST \ https://api.render.com/deploy/srv-d03kjeje5dus73ad5d5g?key=Ronm7PIfxKk
   

