name: Build and deploy JAR app to Azure Web App - back-ame-en-harmonie

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set env variables for tests
        run: |
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> $GITHUB_ENV
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Set Azure App Settings
        run: |
          az webapp config appsettings set \
            --name back-ame-en-harmonie \
            --resource-group <YourResourceGroup> \
            --settings JWT_SECRET=${{ secrets.JWT_SECRET }} CLIENT_URL=${{ secrets.CLIENT_URL }}

      - name: Deploy JAR to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'back-ame-en-harmonie'
          slot-name: 'Production'
          package: '*.jar'
