package com.doranco.project.enums;

public enum CategoryEnum {
    DEPRESSION,TROUBLE_INSOMNIE_ANXIETE,TROUBLE_PANIQUE, PHOBIE,
    PHOBIE_SPECIFIQUE,
    TOC,
    TROUBLE_BIPOLAIRE,
    ADDICTION,
    TROUBLE_SOMATIQUE,
    INTERVENTION_IMMEDIATE_NECESSAIRE,
    TROUBLE_SPECTRE_AUTISTIQUE,
    CONSULTATION_PROFESSIONNELLE_RECOMMANDEE
}
